### PR TITLE
fix: search parent directories to find repository

### LINKED ISSUE #41: Default to using `Repo(".")` rather than checking parent dir for subdirs
Relevant here: https://github.com/backstage/mkdocs-techdocs-core/issues/38#issuecomment-1544153331

https://github.com/ojacques/mkdocs-git-committers-plugin-2/blob/d9cd87ab14c6aed9f4db36892c4d8bdc137544cb/mkdocs_git_committers_plugin_2/plugin.py#L79

Checklist:
- [x] Non-empty github token.

### PR DESCRIPTION
**Pull request by thor**
Fixes #41.

Allows for repositories where their documentation pipeline is not run from the root directory, e.g. a documentation repository where `mkdocs.yml` is at `docs/mkdocs.yml`, along with e.g. `docs/pyproject.toml`.

Particularly relevant for non-Python projects and monorepos.

### CODE REVIEW

**Comment by ojacques** [comment]
Thanks! I will merge this when I get back in front of a keyboard.

**Comment by thor** [comment]
> Thanks! I will merge this when I get back in front of a keyboard.

Thanks for the prompt reply! Looking forward to it; if you may, let me know if it'll take a bit longer or if I may be of help.

**Comment by lord-vesel** [comment]
It must be configurable and defaults to false

**Comment by thor** [comment]
> It must be configurable and defaults to false
> 
> Like this: #48 

Could you explain why, @lord-vesel?

Not that I personally mind, and it's not my call as I'm not a maintainer here, but I believe fewer configuration options are better unless there's a solid use-case and associated problem to explain why it is needed. 

Especially the default: which scenario does this break?

**Comment by ojacques** [comment]
Looks good to me, at least as first step. I will comment on @lord-vesel 's PR and find out the use case. Thanks both.

**Pull request merged**
