### PR TITLE
Retrieve author login from commit info

### PR DESCRIPTION
**Pull request by adamant-pwn**
Should work even when author didn't set public email.

### CODE REVIEW

**Comment by adamant-pwn** [comment]
Sorry, this needs some further changes, testing it locally rn.

**Comment by adamant-pwn** [comment]
@ojacques hi, could you review this change now, please? I think I mostly fixed all the bugs from the initial PR version.

On https://github.com/e-maxx-eng/e-maxx-eng, my PR reduces the number of users without found logins from 21 to just 3. And the build time without cached authots.json changed for me locally from 195s to 125s.

**Comment by ojacques** [comment]
This is a nice improvement. Thank you so much. Yet, when testing against another repo (https://github.com/squidfunk/mkdocs-material), `squidfunk` for example is not identified where he used to be. Let me know if you can have a look, or I'll see what I can find.

**Comment by byhemechi** [comment]
This is a pretty major issue, my github profile is always resolved to Geosynchronous (assumedly based on my first name)

**Comment by ojacques** [comment]
> Sure, I can look. Could you point to a specific page where it occurs?

Yes, this is the [repository for `mkdocs-material`](https://github.com/squidfunk/mkdocs-material).

> This is a pretty major issue, my github profile is always resolved to Geosynchronous (assumedly based on my first name)

Sorry to read that. I hope we can find a solution which works in all cases.

**Comment by matoszz** [comment]
is it due to the fact the match is on name first vs. github user handle? My user today is incorrectly matched because it's looking for "matt anderson" and not @matoszz

**Comment by ojacques** [comment]
@adamant-pwn - looking into this again. This PR is important and I want to move forward with it.

I do have several comments:

- The cache file does not have the same elements than current version. Could you include some logic to avoid throwing an error?

```
  File "/home/oja/.local/lib/python3.10/site-packages/mkdocs_git_committers_plugin_2/plugin.py", line 215, in on_pre_build
    for email in info['emails']:
KeyError: 'emails'
```
- When running on mkdocs-material repo (and I guess this would be the same for others), with the `MKDOCS_GIT_COMMITTERS_APIKEY` env variable set, the logic keeps on looking up for the same user info. This should be looked up from the cache after the first attempt.

```
INFO     -  git-committers plugin ENABLED
WARNING  -  no git token provided and MKDOCS_GIT_COMMITTERS_APIKEY environment variable is not defined
INFO     -  Get user info from GitHub for: martin.donath@squidfunk.com based on commit
            7e62a797b167ea27dbdc5ed9e19f3bc46f962613
INFO     -  Commit-based search failed, falling back on user-based search
INFO     -  Get user info from GitHub for: martin.donath@squidfunk.com based on commit
            efbd2284724b01bf7e1db0c9137a9367b9bb321e
INFO     -  Commit-based search failed, falling back on user-based search
INFO     -  Get user info from GitHub for: martin.donath@squidfunk.com based on commit
            21635acf36dd7cb08c4a7a901a2d29481f9635ab
```
- When setting up the `MKDOCS_GIT_COMMITTERS_APIKEY` variable, I get this error and cannot go further:
```
  File "/home/oja/.local/lib/python3.10/site-packages/mkdocs_git_committers_plugin_2/plugin.py", line 221, in on_pre_build
    self.get_git_info(os.path.join(dirpath, filename), pre_run = True)
  File "/home/oja/.local/lib/python3.10/site-packages/mkdocs_git_committers_plugin_2/plugin.py", line 137, in get_git_info
    info = self.get_gitcommit_info( { 'query': """
  File "/home/oja/.local/lib/python3.10/site-packages/mkdocs_git_committers_plugin_2/plugin.py", line 70, in get_gitcommit_info
    info = res['data']['repository']['object']['author']['user']
TypeError: 'NoneType' object is not subscriptable
```

Could you please have a look?

**Comment by adamant-pwn** [comment]
Yes, I will take a look into it.

**Comment by josh-wong** [comment]
Any update on this? This plugin is broken for me as well, with the same behavior that @matoszz mentioned.

> is it due to the fact the match is on name first vs. github user handle? My user today is incorrectly matched because it's looking for "matt anderson" and not @matoszz

**Comment by ojacques** [comment]
@matoszz, @josh-wong, @byhemechi - please try now with 0.4.4 release. GitHub login is attempted before GitHub user name. Please comment under issue #7 - as this PR has more changes than just switching login / name. Thanks!

**Comment by ojacques** [comment]
Given the rewrite and change of method to get the list of contributors in 1.0.0, this PR does not need to stay opened.
Thank you so much for this @adamant-pwn, this is lots of great work. Let me know how 1.0.0 works for you.

**Comment by adamant-pwn** [comment]
Hey @ojacques, thanks for the update! In my case, I combine this plugin with [git-authors-plugin](https://timvink.github.io/mkdocs-git-authors-plugin/usage.html), as it also computes the contribution percentage of every author. But that plugin only works with names and emails, and the later is more reliable identifier, so I wonder if it is possible to also include author's emails (or maybe some email-to-id map) into `self.authors` table?

**Pull request closed without merging**
